app/config/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

app/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.page_index, name='index'),
    path('products/', views.products, name='products'),
    path('products/<int:pk>/', views.product, name='product'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/edit/<int:pk>/', views.edit_product, name='edit_product'),
    path(
        'products/delete/<int:pk>/',
        views.remove_product,
        name='remove_product',
    ),
]

app/store/models.py
from django.db import models
from django.utils.text import slugify


class Product(models.Model):
    class Status(models.TextChoices):
        ACTIVE = 'A', 'Activated'
        INACTIVE = 'I', 'Inactivated'

    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100)
    description = models.TextField(blank=True, default='')
    price = models.DecimalField(decimal_places=2, max_digits=8)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=1,
        choices=Status.choices,
        default=Status.INACTIVE,
    )
    category = models.ForeignKey(
        'Category',
        null=True,
        on_delete=models.SET_NULL,
        related_name='products',
    )

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(
                fields=['name'],
            )
        ]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __repr__(self) -> str:
        return f'{super().__class__.__name__}(name={self.name!r})'


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=30)
    description = models.TextField(blank=True, default='')

    class Meta:
        ordering = ['pk']

    def __repr__(self) -> str:
        return f'{super().__class__.__name__}(name={self.name!r})'

    def __str__(self) -> str:
        return self.name

app/store/forms.py
from django import forms

from .models import Category, Product

TEXTINPUT_CLASSES = 'block w-full mb-2 rounded-md bg-white/5 px-3 py-1.5 text-base outline-1 -outline-offset-1 outline-white/10 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500'


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product

        fields = (
            'name',
            'description',
            'price',
            'category',
            'status',
        )
        labels = {
            'name': 'Title',
            'description': 'Description',
            'price': 'Price',
            'category': 'Category',
            'status': 'Status',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': TEXTINPUT_CLASSES}),
            'description': forms.Textarea(attrs={'class': TEXTINPUT_CLASSES}),
            'price': forms.NumberInput(attrs={'class': TEXTINPUT_CLASSES}),
            'category': forms.Select(attrs={'class': TEXTINPUT_CLASSES}),
            'status': forms.Select(attrs={'class': TEXTINPUT_CLASSES}),
        }


class RemoveProductForm(forms.Form):
    confirm = forms.BooleanField(
        required=True,
        label='Do you really want to remove?',
        widget=forms.CheckboxInput(
            attrs={
                'class': 'col-start-1 row-start-1 appearance-none rounded-sm border border-white/10 bg-white/5 checked:border-indigo-500 checked:bg-indigo-500 indeterminate:border-indigo-500 indeterminate:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 disabled:border-white/5 disabled:bg-white/10 disabled:checked:bg-white/10 forced-colors:appearance-auto',
                'id': 'confirm',
            }
        ),
    )

app/store/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import AddProductForm, RemoveProductForm
from .models import Category, Product


# Create your views here.
def page_index(request):
    return render(request, 'store/index.html')


def products(request):
    products = Product.objects.all()
    paginator = Paginator(products, 8)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
    }

    return render(request, 'store/products.html', context)


def product(request, pk):
    product = get_object_or_404(Product, pk=pk)

    context = {
        'product': product,
    }

    return render(request, 'store/product.html', context)


def add_product(request):
    if request.method == 'POST':
        form = AddProductForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('store:index')

    else:
        form = AddProductForm()

    return render(request, 'store/add_product.html', {'form': form})


def edit_product(request, pk):
    product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        form = AddProductForm(instance=product)

        if form.is_valid():
            form.save()
            return redirect('store:product', pk=pk)

    else:
        form = AddProductForm(instance=product)

    context = {
        'form': form,
        'product': product,
    }

    return render(request, 'store/edit_product.html', context)


def remove_product(request, pk):
    product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        form = RemoveProductForm(request.POST)
        if form.is_valid():
            product.delete()
            return redirect('store:products')
    else:
        form = RemoveProductForm()

    context = {
        'form': form,
        'product': product,
    }

    return render(request, 'store/remove_product.html', context)

app/store/templates/store/add_product.html
{% extends 'base.html' %}

{% block title %}
  Add Product{{ block.super }}
{% endblock %}

{% block content %}
  <form method="post" class="my-4 mx-auto max-w-2xl">
    {% csrf_token %}
    <div class="mt-4 pb-4 border-b border-white/10">
      <h2 class="font-semibold text-white mb-4">Add new Product</h2>
      {{ form }}
    </div>
    <div class="mt-6 flex items-center gap-x-6">
      <button type="submit" class="rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">Add</button>
      <button type="button" class="text-sm/6 font-semibold text-white">Cancel</button>
    </div>
  </form>
{% endblock %}

app/store/templates/store/edit_product.html
{% extends 'base.html' %}

{% block title %}
  Edit Product "{{ product.name }}"{{ block.super }}
{% endblock %}

{% block content %}
  <form method="post" class="my-4 mx-auto max-w-2xl">
    {% csrf_token %}
    <div class="mt-4 pb-4 border-b border-white/10">
      <h2 class="font-semibold text-white mb-4">Edit product</h2>
      {{ form }}
    </div>
    <div class="mt-6 flex items-center gap-x-6">
      <button type="submit" class="rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">Save</button>
      <a href="{% url 'store:product' product.pk %}" class="text-sm/6 font-semibold text-white">Cancel</button>
    </div>
  </form>
{% endblock %}

app/store/templates/store/index.html
{% extends "base.html" %}

{% block title %}Main Page{{ block.super }}{% endblock title %}

{% block content %}
<div class="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
    <div class="text-center">
    <h1 class="text-5xl font-semibold tracking-tight text-balance text-white sm:text-7xl">
        {% block page_header %}Welcome to Our Django Shop!{% endblock page_header %}
    </h1>
    <p class="mt-8 text-lg font-medium text-pretty text-gray-400 sm:text-xl/8">
        {% block page_content %}Here You can buy everything you need.{% endblock page_content %}
    </p>
</div>
{% endblock content %}

app/store/templates/store/product.html
{% extends 'base.html' %}

{% block title %}
  {{ product.name }}{{ block.super }}
{% endblock %}

{% block content %}
  <div class="mx-auto max-w-2xl mt-3 pb-4 text-gray-300">
    <h1 class="text-2xl pb-4">{{ product.name }}</h1>
    <div class="my-6">
      <h2>Product price</h2>
      <p class="text-3xl text-gray-200">{{ product.price }} ₽</p>
    </div>
    {% if product.description %}
      <div>
        <h3 class="text-xl">Description</h3>
        <p class="text-base text-gray-300">{{ product.description }}</p>
      </div>
    {% endif %}
    <form action="{% url 'store:edit_product' product.pk %}" method="post" class='border-t border-white/10 mt-4 pt-4'>
      {% csrf_token %}
      <div class="flex items-center gap-x-6">
        <button type="submit" class="rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold">Edit</button>
        <a href="{% url 'store:remove_product' product.pk %}" type="button" class="rounded-md bg-orange-800 px-3 py-2 text-sm font-semibold">Remove</a>
      </div>
    </form>
  </div>
{% endblock %}

app/store/templates/store/products.html
{% extends 'base.html' %}
{% block title %}
  Products{{ block.super }}
{% endblock %}

{% block content %}
  <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <div class="mt-6 mb-4 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
      {% for product in page_obj.object_list %}
        <div class="group relative bg-gray-200 border-5 rounded-xl overflow-hidden">
          <a href="{% url 'store:product' product.pk %}">
            <img src="https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg" alt="{{ product.name }}" />
            <div class="flex flex-col items-center my-2">
              <h3 class="text-m text-gray-700">{{ product.name }}</h3>
              <h4 class="text-gray-600">{{ product.price }} ₽</h4>
            </div>
          </a>
        </div>
      {% empty %}
        --- Товаров сейчас нет ---
      {% endfor %}
    </div>
    <div class="flex items-center justify-between border-t border-white/10 px-4 py-3 sm:px-6">
      <div class="flex flex-1 justify-between sm:hidden">
        <a href="#" class="relative inline-flex items-center rounded-md border border-white/10 bg-white/5 px-4 py-2 text-sm font-medium text-gray-200 hover:bg-white/10">Previous</a>
        <a href="#" class="relative ml-3 inline-flex items-center rounded-md border border-white/10 bg-white/5 px-4 py-2 text-sm font-medium text-gray-200 hover:bg-white/10">Next</a>
      </div>
      <div class="hidden sm:flex sm:flex-1 sm:items-center sm:justify-between">
        <div>
          <p class="text-sm text-gray-300">
            Showing
            <span class="font-medium">{{ page_obj.start_index }}</span>
            to
            <span class="font-medium">{{ page_obj.end_index }}</span>
            of
            <span class="font-medium">{{ page_obj.paginator.count }}</span>
            results
          </p>
        </div>
        <div>
          <nav aria-label="Pagination" class="isolate inline-flex -space-x-px rounded-md">
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" disabled class="relative inline-flex items-center rounded-l-md px-2 py-2 text-gray-400 inset-ring inset-ring-gray-700 hover:bg-white/5 focus:z-20 focus:outline-offset-0">
              <span class="sr-only">Previous</span>
              <svg viewBox="0 0 20 20" fill="currentColor" data-slot="icon" aria-hidden="true" class="size-5">
                <path d="M11.78 5.22a.75.75 0 0 1 0 1.06L8.06 10l3.72 3.72a.75.75 0 1 1-1.06 1.06l-4.25-4.25a.75.75 0 0 1 0-1.06l4.25-4.25a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" fill-rule="evenodd" />
              </svg>
            </a>
            {% endif %}
            {% for page_num in page_obj.paginator.page_range %}
              {% if page_obj.number == page_num  %}
                <a href="?page={{ page_num }}" aria-current="page" class="relative z-10 inline-flex items-center bg-indigo-500 px-4 py-2 text-sm font-semibold text-white focus:z-20 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">{{ page_num }}</a>
              {% else %}
                <a href="?page={{ page_num }}" class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-200 inset-ring inset-ring-gray-700 hover:bg-white/5 focus:z-20 focus:outline-offset-0">{{ page_num }}</a>
              {% endif %}
            {% endfor %}
            {% comment %} <span class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-400 inset-ring inset-ring-gray-700 focus:outline-offset-0">...</span> {% endcomment %}
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="relative inline-flex items-center rounded-r-md px-2 py-2 text-gray-400 inset-ring inset-ring-gray-700 hover:bg-white/5 focus:z-20 focus:outline-offset-0">
              <span class="sr-only">Next</span>
              <svg viewBox="0 0 20 20" fill="currentColor" data-slot="icon" aria-hidden="true" class="size-5">
                <path d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" fill-rule="evenodd" />
              </svg>
            </a>
            {% endif %}
          </nav>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/store/templates/store/remove_product.html
{% extends 'base.html' %}

{% block title %}
  Remove "{{ product.name }}"{{ block.super }}
{% endblock %}

{% block content %}
<form method="post" class="my-4 mx-auto max-w-2xl">
  {% csrf_token %}
  <div class="mt-4 pb-4 border-b border-white/10">
    <h2 class="font-semibold text-white mb-4">Remove Product "{{ product.name }}"</h2>
    <div class="flex items-center gap-2">
      <div class="group grid size-4 grid-cols-1">
        {{ form.confirm.as_widget }}
        <svg viewBox="0 0 14 14" fill="none" class="pointer-events-none col-start-1 row-start-1 size-3.5 self-center justify-self-center stroke-white group-has-disabled:stroke-white/25">
          <path d="M3 8L6 11L11 3.5" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="opacity-0 group-has-checked:opacity-100" />
          <path d="M3 7H11" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="opacity-0 group-has-indeterminate:opacity-100" />
        </svg>
      </div>
      <label for="confirm" class="text-base text-gray-300">{{ form.confirm.label }}</label>
    </div>
    {% if form.confirm.errors %}
      <p class="text-sm text-red-600">{{ form.confirm.errors.0 }}</p>
    {% endif %}
  </div>
  <div class="mt-6 flex items-center gap-x-6">
    <button type="submit" class="rounded-md bg-orange-800 px-3 py-2 text-sm font-semibold text-white focus-visible:outline-orange-800">REMOVE</button>
    <a href="{% url 'store:product' product.pk %}" class="text-sm/6 font-semibold text-white">Cancel</a>
  </div>
</form>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  <title>{% block title %} :: Django Shop{% endblock title %}</title>
</head>

<body class="bg-gray-700 h-screen">
  {% include "includes/header.html" %}
  <main>
    {% block content %}No content{% endblock content %}
  </main>
</body>

</html>

app/templates/includes/header.html
<header class="bg-gray-900">
  <nav class="flex items-center justify-around p-6 px-8 text-white">
    <div class="flex gap-x-10">
      <a href="{% url 'store:index' %}" class="text-sm/6 font-semibold">🏠</a>
      <a href="{% url 'store:products' %}" class="text-sm/6 font-semibold">Our Products</a>
      <a href="{% url 'store:add_product' %}" class="text-sm/6 font-semibold">Add New Product</a>
    </div>
    <div class="">
      {% if request.user.is_authenticated %}
        Welcome, {{ request.user.username }}! <a href="{% url 'admin:index' %}" class="text-xs text-blue-300">Admin Panel</a>
      {% else %}
        <a href="{% url 'admin:index' %}" class="text-xs text-blue-300">Admin Panel</a>
      {% endif %}
    </div>
  </nav>
</header>